# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.x'
  displayName: 'Install latest NuGet Exe version'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
  displayName: 'NuGet Restore'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    restoreNugetPackages: false
    msbuildArchitecture: 'x64'
  displayName: 'Build solution'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    testRunTitle: 'Calculator Tests'
  displayName: 'Run xUnit Test'